[functions]
  directory = "be/functions"
  external_node_modules = ["@nestjs/common", "@nestjs/swagger", "@nestjs/microservices", "@nestjs/websockets/socket-module", "emitter", "vm2",  "be/dist/app"]
  included_files = ["be/dist/*"]
  node_bundler = "esbuild"
  
